# Generated by Django 4.0.6 on 2022-10-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gp',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
